### ISSUE TITLE
Добавить событие response

### ISSUE THREAD

**Issue by vitalets** [fletcherist/yandex-dialogs-sdk#114]
Хочется добавить событие `response`, которое бы тригерилось, когда ответ уже сформирован. Это пригодится например для отправки аналитики.

Примерно так:
```js
const alice = new Alice();

alice.command('Привет', ctx => { ... });

alice.on('response', ctx => {
  console.log(ctx.response);
});
```

**Comment by popstas** [comment]
+1, я сейчас проблему решаю так: все ответы проходят через мою функцию reply, где [триггерится onShutdown](https://github.com/popstas/yandex-dialogs-whatis/blob/master/src/middlewares/reply.js#L106), ваш вариант мне больше нравится.

**Comment by vitalets** [comment]
Да. Особенно для https://github.com/popstas/yandex-dialogs-sdk-chatbase пригодится )

**Comment by vitalets** [comment]
Нашел еще способ через метод `alice.handleRequest`, который используется в [примере](https://github.com/fletcherist/yandex-dialogs-sdk/blob/master/examples/aliceExpress.js) с express-ом:
```js
app.use(bodyParser.json());
app.post('/webhookurl', async (req, res) => {
  const jsonAnswer = await alice.handleRequest(req.body);
  // analytics goes here 
  res.json(jsonAnswer);
});
app.listen(8080);
```

**Comment by fletcherist** [comment]
Да, действительно, кто пользуется `alice.listen()` — теряет возможность смотреть все ответы. 
способ 
```ts
alice.on('response', ctx => {
  console.log(ctx.response);
});
```
тут бы круто сработал

Взял задачу в разработку. Ща закину PR

**Comment by fletcherist** [comment]
Done here: https://github.com/fletcherist/yandex-dialogs-sdk/commit/52e1a794eab75ff876a1c9b0725ca85deb6f1cf4

lets mark as resolve, if no one has any questions yet :)

**Comment by vitalets** [comment]
Огонь! 👍 
А в ридми может тоже добавить?

**Comment by fletcherist** [comment]
@vitalets А я запилил сразу же https://github.com/fletcherist/yandex-dialogs-sdk/commit/54e121f66322a7ae92c6cf75648bb895ccb15744

Только забыл в issue отписаться, да =)

**Comment by vitalets** [comment]
Выяснилась некоторая деталь: `ctx` который прилетает в листенер - не тот же самый, что в обработчике `alice.any(ctx => ...)`

```js
alice.any(ctx => {
    ctx.intent = 'intent';
    return {text: 'hello'};
});

alice.on('response', ctx => {
    console.log(ctx.intent); // => undefined
});
```

**Comment by fletcherist** [comment]
@vitalets 
Запилил фикс в #115 
теперь контекст из мидлварей (стейдж — просто одна из них) прокидывается в листенер правильно

**Comment by fletcherist** [comment]
Также добавил событие `request`  для консистентности
`alice.on('request', ...)`

**Comment by fletcherist** [comment]
Released as `2.2.0`

**Comment by vitalets** [comment]
Спасибо! 👍
