### ISSUE TITLE
Неиспользуемые файлы в репозитории

### ISSUE THREAD

**Issue by sameoldmadness** [fletcherist/yandex-dialogs-sdk#2]
В репозитории лежит несколько неиспользуемых файлов, которые стоит убрать.

- `.babelrc`
- `.flowconfig`
- `package-lock.json` и `yarn.lock` – [не нужны](https://docs.npmjs.com/files/package-lock.json) в библиотеке.

> One key detail about package-lock.json is that it cannot be published, and it will be ignored if found in any place other than the toplevel package.

Заодно можно прибраться в зависимостях.

- micro не нужен
- eslint нужен в dev

Из `.eslintrc` можно убрать упоминание flowtype.

**Comment by fletcherist** [comment]
@sameoldmadness Спасибо! Разрабатывался в режиме хакатона и совершенно не обратил на это внимания :) 

Всё поправил. Ещё раз спасибо за issue 👍
