### ISSUE TITLE
Проблема leave и enter команд сцены

### ISSUE THREAD

**Issue by rogodec** [fletcherist/yandex-dialogs-sdk#32]
Сейчас enter и leave срабатывает только при полном совпадении, мне кажется надо бы  переделать на поиск, который используется в командах.
Еще из-за того, что входная команда сейчас в общем списке команд сцены она может выбраться при команд поиске уже внутри сцены

**Comment by fletcherist** [comment]
Согласен. Крутой наброс.
Кажется, что хорошо бы сделать фуззи-поиск по точке входа и выхода из команды, а также убрать `enter` хандлер из поиска внутри сцены
