### ISSUE TITLE
Matchers+

### ISSUE THREAD

**Issue by rogodec** [fletcherist/yandex-dialogs-sdk#34]
Дополнение к issue #30 
Очень нужный функционал, но предлагаю не использовать функцию как аргумент, а использовать объект. При использовании объекта можно будет делать проверки сразу по нескольким параметрам (команде от пользователя, данным в сессии и своей функции, куда придет ctx) и будет возможность безболезненно масштабировать функционал.
Как пример возможной реализации:
```javascript
alice.command({
  speech: 'Привет!', /* Проверка по фразе, как сейчас */ 
  data: [{ key: 'step', value: 'welcome' }], /* Массив объектов для проверки по данным в сессии */ 
  additional: (ctx) => { return ctx.session.getData('step') === 'welcome' } // Своя функция обработчик, в которую приходит ctx 
}, ctx => ctx.reply('Добрый день!')
```

**Comment by fletcherist** [comment]
А тут получается, что все три пункта должны срабатывать, чтобы перейти в эту команду?

**Comment by fletcherist** [comment]
@rogodec  А как быть, если какое-нибудь значение в сессии надо посчитать асинхронно? Тогда этот API начнёт просыпаться. Идея была сделать функцию **матчер** и отдать ей приоритет перед поиском по *строкам/массивом строк/регулярками*. Матчер может быть асинхронным и может запросто реализовывать функциональность, которую ты описал выше. Кроме того, он может делать это асинхронно.

Как вариант для обсуждения предлагаю такую реализацию

```javascript
async function handleAsObject(ctx) {
  const obj = {
    speech: 'Привет!', /* Проверка по фразе, как сейчас */ 
    data: [{ key: 'step', value: 'welcome' }], /* Массив объектов для проверки по данным в сессии */ 
    additional: (ctx) => { return ctx.session.getData('step') === 'welcome' } // Своя функция обработчик, в которую приходит ctx 
  }
  if (ctx.message === obj.speech && additional(ctx) && ...) {
      return true
  }
  return false
}

alice.command(
  async (ctx) => await handleAsObject(ctx),
  ctx => ctx.reply('Добрый день!')
)
```

Но, если честно, тут надо, чтобы что-нибудь сказал ещё @popstas, как автор этих матчеров, потому что у меня сейчас не очень полное понимание, чего мы всё таки хотим.

Кажется, что фишка матчеров — возможность матчить комманды асинхронно, например, подтянуть сессию и посмотреть там что-нибудь или вообще мидлварь заюзать из контекста какую-нибудь, например:
```javascript
// Если матчер возвращает true, заходим в него
alice.command(async (ctx) => await ctx.isAuthenticated(),
     ctx => ctx.reply('Вы неавторизованы')
)
alice.command('Приватная команда',
     ctx => ctx.reply('Вы прошли авторизацию, теперь пользоваться можно')
```

**Comment by popstas** [comment]
Я так и представляю себе этот функционал, как @fletcherist выше описал.

Вообще, я думал про матчеры, потому что:
- они очень похожи на мидлвари команд
- они дают возможность реализовать любую логику совпадения

Через объект пройдет то, что мы придумаем сейчас (speech, data, additional), но потом надо будет расширять. Мне кажется, что в результате в этом объекте будет много разных полей, где в каждом конкретном случае, например, из 10 параметров надо указать 2-3, а остальные - для других случаев.

Если сделать матчеры, то можно по идее не только реализовать пример из этого issue как один из матчеров, но и переделать встроенные матчеры по strings, regexps и figures на матчеры. Это даст возможность подменять их на свои, когда встроенные чем-то не устраивают (например, работа fuse  в матчере строк).

Также, с матчерами масштабироваться должно быть легче: вместо расширения одного объекта можно делать несколько разных матчеров для разной логики.

**Comment by popstas** [comment]
@rogodec, с матчером можно же написать функцию с параметрами, которая реализует твою логику, читабельность практически не ухудшится, будет типа такого:
``` js
alice.command(
  async (ctx) => return await handleAsObject(ctx, {
    speech: 'Привет!', /* Проверка по фразе, как сейчас */ 
    data: [{ key: 'step', value: 'welcome' }], /* Массив объектов для проверки по данным в сессии */ 
    additional: (ctx) => { return ctx.session.getData('step') === 'welcome' } // Своя функция обработчик, в которую приходит ctx 
  }),
  ctx => ctx.reply('Добрый день!')
)
```

**Comment by rogodec** [comment]
Примерно то на то и выходит, тут надо подумать над тем, что чаще будет использоваться. Я предполагал, что в первую очередь будет большое количество команд как раз запрос юзера + данные из сессии или просто данные из сессии, а кастомная функция на фоне их будет использоваться редко. Если я в этом не прав, то конечно лучше вариант с функцией.
Просто в моем навыке чуть больше 30 команд и почти все из них завязаны на данных сессии, которые нужно проверить на наличие или на какое-то значение, чтобы провалиться в команду, где уже более тщательная обработка запроса, а кастомная функция всего на 2 командах и в итоге используя функцию читабельность очень сильно падает и получается на 50+ строк больше

**Comment by rogodec** [comment]
@popstas @fletcherist в итоге тоже наверное буду за функцию, подумав понял, что профита от объекта никакого. #30
