### ISSUE TITLE
SDK не умеет завершать сессию

### ISSUE THREAD

**Issue by fletcherist** [fletcherist/yandex-dialogs-sdk#40]
Предлагаю сделать метод для `ctx`, аналогичный методу `reply`

Что-то вроде `ctx.endSession()`, `ctx.closeSession()`, `ctx.finishSession()`

Который будет патчить
```JSON
"response": {
    "end_session": true,
```

Предлагайте свои названия! Сделаю в рамках отдельного PR

**Comment by DuckerMan** [comment]
Просто end

**Comment by alexander-karpov** [comment]
goodbye, на человеческом.

**Comment by fletcherist** [comment]
@alexander-karpov Спасибо, реализация понравилась. Уже в мастере. Релиз будет скоро. В 1.4.7 функциональность выкатится
