### ISSUE TITLE
Scene не наследует fuseOptions от alice

### ISSUE THREAD

**Issue by popstas** [fletcherist/yandex-dialogs-sdk#41]
Мне кажется, правильно будет пробрасывать fuseOptions, переданные при создании alice.
Сейчас, после #39, если fuseOptions нужно задавать для каждой сцены: 
``` js
new Scene('in-answer', { fuseOptions })
```

**Comment by popstas** [comment]
С другой стороны, как она будет наследовать, я что-то не заметил, что сцена создается через new Scene, а не через alice.scene()

**Comment by fletcherist** [comment]
@popstas Кстати, это интересное предложение добавить `alice.scene('name')`, чтобы не использовать пропиетарные `new` и классы снаружи.

**Comment by fletcherist** [comment]
No fuse.js anymore, so I'll close this, if you don't mind
