### ISSUE TITLE
fuse.js всегда совпадёт со строкой длиннее 32 символов

### ISSUE THREAD

**Issue by popstas** [fletcherist/yandex-dialogs-sdk#42]
Оригинальный баг - https://github.com/krisk/Fuse/issues/136
Ответа там нет, посмотрел PR, последние коммиты в форках, там тоже нет исправления, но в issue есть указание место на проблемную строку.

При длине строки длиннее 32 в совпадениях будут рандомные строки, все со score 0.5, ни больше ни меньше.

Варианты решения (по убыванию моих предпочтений):
- обрезать строки до 32
- не использовать fuse.js при строках длиннее 32
- выкинуть fuse.js (но чем его заменить?)

**Comment by popstas** [comment]
Наверное да, лучше уж тогда сделать его в виде опционального матчера, с описанием багов. А как тогда проверять, просто полное соответствие без учета регистра?

**Comment by fletcherist** [comment]
@popstas кажется, что можно использовать решение от https://github.com/bevacqua/fuzzysearch, дополнительно кастомизировав его под себя

**Comment by fletcherist** [comment]
Например, предложение разбивать на токены `ctx.message.split(' ')` и запускать `fuzzysearch` на каждый токен, считать скор и выдавать с наибольшим.

Или запускать `fuzzysearch` на целую фразу и искать **первого** совпадения

**Comment by popstas** [comment]
Мне кажется, что это сильно зависит от того, что требуется от навыка: отвечать на как можно большее кол-во запросов (компенсируя незнание юзером точных команд, неправильно распознанных слов и т.д.) или делать как можно меньше ложных срабатываний.

Думаю, что надо давать возможность давать легко использовать оба варианта.

Лично я в своем навыке выбираю четкий поиск, по-моему, проблему нечеткого поиска надо не просто fuzzy search решать, а с помощью какого-то NLP.

Для себя я проблему пока решил, написав [простой матчер](https://github.com/popstas/yandex-dialogs-whatis/blob/master/src/matchers.js), который у меня заменяет сейчас текущее решение в sdk.

**Comment by fletcherist** [comment]
PR #43

**Comment by fletcherist** [comment]
@popstas We refused from using `fuse.js`. Furthermore for default for `string` handlers we're now using [levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance) algorithm
