### ISSUE TITLE
npm package cause TypeScript compiler errors

### ISSUE THREAD

**Issue by Yavanosta** [fletcherist/yandex-dialogs-sdk#47]
Looks like not all required types included into npm package.

 For example if you look into `alice.d.ts` in dist folder in reference `import { configInterface } from './types/alice';` but there is no `'./types/alice'` file here.

So I can't use this package with typescript :-(

**Comment by fletcherist** [comment]
We're working on this at PR https://github.com/fletcherist/yandex-dialogs-sdk/pull/55

**Comment by fletcherist** [comment]
Fixed in **v1.4.7**
