### ISSUE TITLE
Выводить original_utterance в ctx

### ISSUE THREAD

**Issue by popstas** [fletcherist/yandex-dialogs-sdk#52]
У меня в навыке смысл зависит от того, с какой фразой вызвали навык. "Спроси у ..." - чтение "Скажи ..." - запись. Поэтому понадобилось читать `original_utterance`, а к ней нет доступа из SDK.

**Comment by popstas** [comment]
Оказалось, что доступ есть: `ctx.req.request.original_utterance`

**Comment by fletcherist** [comment]
@popstas отличная идея, `ctx.req.request.original_utterance` — длинный путь. Предлагаю `ctx.original_utterance`, потому что скоро буду прокачивать механизм матчинга с командами и он там очень сильно понадобится, я буду работать именно с ним, а не с `ctx.message`

**Comment by fletcherist** [comment]
solved here: PR https://github.com/fletcherist/yandex-dialogs-sdk/pull/62

**Comment by fletcherist** [comment]
@popstas ctx.originalUtterance
