### ISSUE TITLE
CONTRIBUTING.md

### ISSUE THREAD

**Issue by fletcherist** [fletcherist/yandex-dialogs-sdk#54]
Мы решили ввести гугловый кодстайл, чтобы весь проект был консистентным 
http://google.github.io/styleguide/jsguide.html

Нужен гайд для контрибьюторов `CONTRIBUING.md` и ссылка на него в `README.md`.

Туда можно добавить ссылку на кодстайл.
Там можно написать, что мы решили использовать `IButton` вместо `ButtonInterface` для именования интерфейсов в коде.

**Comment by fletcherist** [comment]
Уже не актуально. @alexander-karpov принёс `prettier` — повесим на прекоммит хук. Он за стиль будет разруливать

**Comment by alexander-karpov** [comment]
@fletcherist Вообще за стиль хорошо бы настроить eslint, он typescript умеет и нормально дружит с prettier. Ну или tslint. Сейчас оба подключены, но ни один не используется.

**Comment by fletcherist** [comment]
@alexander-karpov ненене, если ты подлючаешь `prettier`, то за стили хорошо бы, чтобы разруливал он, потому что у `eslint` могут возникать диалектические трактовая кода (когда он скатывается в `while true` и не знает, какой вариант выбрать.

`prettier` же работает только в одну сторону, поэтому кажется логичным одного заставить работать только на форматирование и кодстайл, а другого — на поиск ошибок вроде неиспользуемых переменных и проч.
