### ISSUE TITLE
не разворачивается в тестовой среде

### ISSUE THREAD

**Issue by skvarovski** [fletcherist/yandex-dialogs-sdk#6]
привет, приложение интересное. хотел посмотреть и развернуть его на тестовой среде Now.sh

но нашел ошибку в lowerCamelCase нотации файла, поправь пожалуйста.

Error: Cannot find module './ButtonBuilder'
    at Object.<anonymous> (/home/nowuser/src/node_modules/yandex-dialogs-sdk/src/ctx.js:2:23)

**Comment by fletcherist** [comment]
@skvarovski Привет! Спасибо, что сообщил. Я щас всё поправлю и покрою этот участок тестами :)

**Comment by fletcherist** [comment]
@skvarovski починил, спасибо, если бы ты не написал, так бы и висел баг, потому что на MacOS нечувствительно к регистру.
