### ISSUE TITLE
Об обязательности возвращения результата из команды scene

### ISSUE THREAD

**Issue by popstas** [fletcherist/yandex-dialogs-sdk#60]
Второй раз натыкаюсь на проблему: если из команды сцены не вернуть результат, навык сломается.

В 1.4.7 `ctx.reply()` [перестал возвращать](https://github.com/fletcherist/yandex-dialogs-sdk/blob/7c642307c91d522f1333e673ee2496108f789ad5/src/context.ts#L88) результат, из-за этого все мои сцены сломались (вся одна сцена), т.к. они заканчивались на `return ctx.reply()`, этот пример из README.md тоже должен перестать работать:

``` js
const inBar = new Scene('in-the-bar')
inBar.enter('Алиса, пойдём в бар!', ctx => ctx.reply('Пойдём.'))
inBar.command('ты сейчас в баре?', ctx => ctx.reply('Да!'))
inBar.leave('Пошли отсюда', ctx => ctx.reply('Уже ухожу.'))
```

Если команда сцены не вернет положительный (ненулевой) результат, выполнение продолжится, `commands.search()` найдет и исполнит следующую команду, из-за [этого](https://github.com/fletcherist/yandex-dialogs-sdk/blob/7c642307c91d522f1333e673ee2496108f789ad5/src/alice.ts#L184).

В то же время, если не вернуть результат из обычной команды, ничего страшного не произойдет, в тех же [examples](https://github.com/fletcherist/yandex-dialogs-sdk/blob/7c642307c91d522f1333e673ee2496108f789ad5/examples/aliceListen.js#L9) и [реальных использованиях](https://github.com/sameoldmadness/uraljs-alice-bot/blob/master/index.js#L17) это есть.

Мои предложения:
- Не проверять результат после ответа сцены и всегда прерывать выполнение. Я сейчас не вижу причин не делать этого, может быть в этом есть смысл?
- Вернуть return для `ctx.reply()`, если он был убран не специально (что не имеет смысла, если выполнить первый пункт)
- Программно проверять корректность команды, как ты это [делаешь ](https://github.com/fletcherist/yandex-dialogs-sdk/blob/7c642307c91d522f1333e673ee2496108f789ad5/src/middlewares.ts#L7) в мидлварях, это предупреждение меня спасало от ошибок (опять же не нужно, если убрать первое)

**Comment by alexander-karpov** [comment]
Как насчет того, чтобы вместо вызова `ctx.reply()` использовать возвращаемое значение?
```
inBar.enter('Алиса, пойдём в бар!', () => 'Пойдём.')
inBar.command('Ты сейчас в баре?', () => 'Да!')
```
Сейчас ведь `ctx.reply` обязательно должен быть вызван в обработчике команды и (скорее всего) только один раз - это хорошо подходит для `return`. К тому же возвращаемое значение сейчас не используется.

**Comment by popstas** [comment]
@alexander-karpovl, согласен, возможность возвращать строку в команде была бы удобна, только в предложенном тобой способе внутри sdk наверное будет сложно определить, надо ли использовать возвращаемое значение как ответ, или функция уже ответила и возвращает true или другой малозначащий результат.

Я бы сделал так:
``` js
inBar.command('Ты сейчас в баре?', 'Да!')
```

Это было бы аналогично простому матчеру по строке и запись получается совсем короткая.

**Comment by popstas** [comment]
@alexander-karpov, мне кажется, что через явный вызов функции отвечать правильнее, т.к. все равно будут места, где нельзя просто вернуть строку. В моем навыке `ctx.reply()` используется мало, т.к. почти всегда с ответом возвращаются кнопки.

Матчеры тоже у меня сложные и почти не используется просто одна строка как матчер.

**Comment by alexander-karpov** [comment]
По повожу кнопок: можно сделать чтобы `return` в команде принимал тот же формат, что и `reply`:
```

const { button } = Alice;

alice.welcome(ctx => {
    return {
        text: 'Привет! Я загадала число от 1 до 100. Сможешь отгадать его?',
        buttons: [button('Давай попробуем!'), button('Не хочу')]
    }
});
```

**Comment by popstas** [comment]
Есть еще другие варианты ответа, тогда надо и для них продумать ответ:
- end_session: true
- tts()
- картинки в ответе

Либо написать в доке, что для сложных случаев функции, для простых - возвращать объект в определенном формате.

**Comment by alexander-karpov** [comment]
Да, не клеится что-то. Последний вариант - возвращать результат `ReplyBuilder.get` :)
```
alice.welcome(() =>
    ReplyBuilder.tts(
        'Привет! Я загадала число от 1 до 100. Сможете отгадать его?',
        ReplyBuilder.button('Давай попробуем!'),
        ReplyBuilder.button('Не хочу')
    )
);
```

**Comment by fletcherist** [comment]
Привет! Мне очень понравилось предложение @alexander-karpov сделать возможность отвечать без `ctx.reply`. Это очень круто, давайте так и сделаем. А вот только зачем депрекейтить `ctx.reply`?  Пускай разработчики используют, что хотят. Мне вот, например, нравится явный вызов метода `reply` (потому что так принято во многих фреймворках, и разработчику легче адаптироваться), но, с другой стороны, мне кажется, что обычный `return` чище и логичнее.
```
inBar.enter('Алиса, пойдём в бар!', () => 'Пойдём.')
inBar.command('Ты сейчас в баре?', () => 'Да!')
```

@popstas, крутой вброс, но он ограничивает ветвление сценария. Здесь невозможно ничего проверить и ответить «нет» вместо «да». Вариант возвращать из функции сразу ответ крутой, посколько в нём можно что-то проверять и менять сценарий на лету.
```
inBar.command('Ты сейчас в баре?', 'Да!') // bad
inBar.command('Ты сейчас в баре?', () => 'Да!') // good
```

**Comment by popstas** [comment]
Я понимаю, что проверить ничего нельзя, и в этом такое поведение полностью соответствует поведению матчера-строки ) Вариант bad короче, а good гибче, но почему тогда не:
``` js
inBar.command(() => 'Ты сейчас в баре?', () => 'Да!') // good
```

Меня вот эта неконсистентность только смутила.
А вообще да, если разрешить возвращать строку из любой функции, это будет гибче.
С третьей стороны можно и оба варианта реализовать, в виде функции и в виде строки )

**Comment by alexander-karpov** [comment]
@fletcherist А что ты думаешь по поводу как вернуть tts, кнопки и картинки?

**Comment by fletcherist** [comment]
@alexander-karpov дак так же, смотрите:
https://github.com/fletcherist/yandex-dialogs-sdk/blob/master/src/tests/reply.spec.ts#L35

```javascript
const { reply, image } = Alice
inBar.command('Ты сейчас в баре?', () => {
   return reply({tts: 'да', text: 'да'})) 
}
inBar.any(() => {
   return image(IMAGE_ID)
}
```

**Comment by fletcherist** [comment]
@popstas дак нет никаких проблем так писать. Это уж как разработчик захочет:
```javascript
inBar.command(() => 'Ты сейчас в баре?', () => 'Да!') // good
```

**Comment by alexander-karpov** [comment]
Если никто не против, возьмусь.

**Comment by fletcherist** [comment]
@alexander-karpov we released 2.0 yesterday. Now it supports that syntax:
```javascript
inBar.command(() => 'Ты сейчас в баре?', () => Reply.text('Да!'))
inBar.command(() => 'Ты сейчас в баре?', () => ({text: 'Да!'}))
```

Do we still need to simply return string from handler? I found it to be not very obvious
