### ISSUE TITLE
Рефакторинг Session/Sessions

### ISSUE THREAD

**Issue by fletcherist** [fletcherist/yandex-dialogs-sdk#64]
Кажется, это очень слабое место у нас сейчас.
Я плохо понимаю, чем оно идеологически отличается от `ctx.state`.
Хочется переписать его на мидлвари точно так же, как это было сделано с `ctx.state`

**Comment by popstas** [comment]
Согласен, они очень похожи, по-моему разница в том, что session должен сбрасываться при каждом заходе в навык (начало сессии), а в state персиститься для каждого юзера

**Comment by fletcherist** [comment]
Refactoring is done, guys! We dropped out `state`.
Now only `ctx.session`
`session.get() session.set(data, anything)`
