### ISSUE TITLE
Более плавный переход от reply('текст') к reply с указанием tts.

### ISSUE THREAD

**Issue by xoposhiy** [fletcherist/yandex-dialogs-sdk#76]
## Больной сценарий

1. Пишешь в коде: `reply('неверный перевод слова')`.
2. Получаешь неправильное ударение "слова́".
3. Приходится стирать все и переписывать на использование replyBuilder, да ещё и дублировать всю фразу. А всего-то нужно ударение исправить. В итоге ленишься и оставляешь как есть. Качество навыка страдает.

## Предложение

Ввести спец-синтаксис в reply, в котором можно указать инструкцию для tts. Что-нибудь в духе такого:

```
ctx.reply('неверный перевод {{слова|сл+ова}} {{C#|си шарп}}') 
```

Это может быть эквивалентно 
```
ctx.reply(ctx.replyBuilder
  .text('неверный перевод слова C#') 
  .tts('неверный перевод сл+ова си шарп')
  .get());
```

**Comment by alexander-karpov** [comment]
Чтобы не городить парсинг таких шаблонов, можно использовать _тегированные шаблонные строки_:
```
tts`неверный перевод ${['слова', 'сл+ова']} ${['C#', 'си шарп']}`
```
Это легко можно превратить в вызов `ReplyBuilder` с нужными параметрами.

**Comment by xoposhiy** [comment]
Выглядит красиво. Но я вижу две проблемы с тэггированными шаблонами:

1. Не на столько плавный переход от простой строки к тэггированным строкам.
Надо и вначале строки tts дописать и в конце кавычку исправить и в серёдке переписать. Юзабилити страдает.

2. Больше синтаксического шума: вот лишние символы во втором варианте: tts${['','']} против лишних символов в при парсинге строк: {|}

**Comment by fletcherist** [comment]
@xoposhiy We've released 2.0 recently. Now you can create your own functions to build answers!
Out of box we have `[Reply.text] [Reply.bigImageCard] [Reply.itemsListCard]`

but you can easily create your own
```javascript
const withCorrectTts = message => Reply.text(message.replace(/\+/, ''), {tts: message})
alice.any(ctx => withCorrectTts('сл+ова))
```

equivalent to:
```javascript
{
  text: 'слова',
  tts: 'сл+ова'
}
```

**Comment by fletcherist** [comment]
If you know, how to implement zen function (not like above in my example), which could help to do amazing conversion `text+params` => (text + tts), you can contribute and we'll include it into our core library as one of `Reply` methods
