### ISSUE TITLE
Поддержка вариантивности в ответах на уровне SDK

### ISSUE THREAD

**Issue by xoposhiy** [fletcherist/yandex-dialogs-sdk#77]
Раз уж вы даже в презентации рассказываете, что классно делать вариативность часто повторяющихся фраз, то сделайте поддержку этого в sdk.

Например, так:

```
ctx.reply(`${ctx.oneOf('Привет', 'Здорово')}, ${ctx.oneOf('чувак', 'парниша')}!`);
```
или спец-синтаксисом
```
ctx.reply(`{{Привет|Здорово}}, {{чувак|парниша}}!`);
```

можно даже с вероятностями:

```
ctx.reply(`{{Привет:0.9|Здорово}}, {{чувак:0.5|парниша:0.4|малыш:0.1}}!`);
```

**Comment by fletcherist** [comment]
I fully agree with @alexander-karpov 
It can easily been done. Our tiny library has no need to support additional syntaxes to do this, because everyone has his/her own ideas and plans how to do this particular task
