### ISSUE TITLE
CORS headers

### ISSUE THREAD

**Issue by popstas** [fletcherist/yandex-dialogs-sdk#8]
Привет, я использую приложение на vue как тестовое, которое притворяется Алисой и отправляет запросы на навык.

Проблема в том, что post запросы из браузера не проходят, из-за отсутствия CORS заголовков в ответе yandex-dialogs-sdk.

Возможно ли сделать возможность указать заголовки, не меняя код sdk?

Я пока что прямо в [alice.js listen](https://github.com/fletcherist/yandex-dialogs-sdk/blob/ab508148a714451eef12de40ae31c9ed40935148/src/alice.js#L161) вписал:

``` javascript
      app.use(function(req, res, next) {
        res.header("Access-Control-Allow-Origin", "*")
        res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept")
        next();
      })

```

Это помогло, но хочется по-нормальному сделать. Я вижу, что в alice.js есть middlewares, но они не используются, они предполагались как раз для таких случаев? Если да, могу отправить PR с доделкой этого функционала.

**Comment by fletcherist** [comment]
@popstas Привет! Я пока совсем плохо представляю, как удобнее всего для разработчиков миддлвари реализовать — поэтому это вопрос открытый. Конечно, возможность включения корс-заголовков **через мидлварь** должна быть обязательно! И очень просто включаться.


Правда те middlewares, которые я представлял себе до твоего вопроса, должны были лишь только добавлять дополнительные функциональности к контексту `ctx`. 

Например:
```javascript
alice.use(aliceAuthenticationMiddleware())

alice.any(ctx => {
  // here additional functionality is ctx.isAuthenticated
  if (!ctx.isAuthenticated()) {
    return ctx.reply('Введите пароль:')
  }
  ctx.reply('Добро пожаловать домой!')
})
```

Ну или там какая-нибудь другая мидлварь, которая там, например, будет сохранять сессию пользователя в БД.

```javascript
alice.use(aliceMongoDBSessionMiddleware({...}))

alice.any(ctx => {
  // save this data in background to MongoDB as user session,
  // retrieve in next request etc.
  ctx.session.state.foo = 'bar'
})
```
А вот как это увязать с экспресс-сервером, пока нет идеи, но я щас пойду посмотрю, как это можно попробовать сделать.

Может у тебя есть какое-то видение, как это должно выглядеть архитектурно?

**Comment by popstas** [comment]
По убыванию нормальности :

1. Проще всего открыть доступ к экземпляру express, чтобы напрямую ему делать use, а мидлвари согласен, лучше оставить для ctx. По сути, если твой sdk выставляет правильные заголовки с точки зрения Яндекса, то сложно придумать, зачем еще это может понадобиться, кроме как для отключения CORS на время тестирования.

2. Если правда других использований express не приходит в голову, можно сделать какой-нибудь флаг специально для этой фичи, например, `alice.disableCORS()`.

3. Можно вообще по умолчанию отключать CORS по условию `process.env.NODE_ENV != 'production'`

**Comment by fletcherist** [comment]
Да, это именно оно. Так будет круто! Прокинуть экземпляр express в контекст. И тогда можно написать middleware, который будет делать CORS. Я ща напишу драфт, посмотришь?

**Comment by popstas** [comment]
Да, давай

**Comment by fletcherist** [comment]
UP! Актуально ли ещё?

**Comment by popstas** [comment]
Да, у меня сейчас из-за этого вместо `alice.listen()` используется свой экземпляр express, который дублирует логику из listen и добавляет:
- CORS
- отдачу scenarios.yml

У тебя в примерах мидлварь CORS неправильно написана, думаю, если и делать, то надо не через `alice.use()`, а через `alice.server.use()` делать, это же должно один раз вызваться, а внутри мидлвари будет вызываться при каждом запросе.

**Comment by fletcherist** [comment]
@popstas our new webhook server is implemented on pure `http` module
to add CORS support you can easily use your own server, e.g `express`
[how to do CORS](https://github.com/fletcherist/yandex-dialogs-sdk/blob/master/examples/aliceExpress.js)

1. setup your own server
2. use async handler
3. enable cors by using package `cors` (`npm install cors`)
