### ISSUE TITLE
Version 2.0 READ PLEASE

### ISSUE THREAD

**Issue by fletcherist** [fletcherist/yandex-dialogs-sdk#81]
Hello, mates! 🏷 

I'm very sorry to say, but if u're now working on PR, 99% chance, that it wouldn't be merged in our current release. To tell you the truth, we are going to migrate to `2.0` **with lots of breaking changes** and **new design**

Can't tell you more yet, but you can look at the draft version here: https://github.com/Yavanosta/yandex-dialogs-sdk/tree/v2-preview

We haven't come to consideration with @Yavanosta  in some points yet. Maybe we'll even freeze this repository and continue in another one (thanks to copyright©©© problems)

Stay tuned.

**Comment by Yavanosta** [comment]
It's **VERY** early preview of new version and we still have a lot of things to discuss. If you have some view on design of library please write everything here and lets discuss.

Key points of v2.0 version:
1. Rewritten on Typescript from scratch with maximum strict compiler options, including strictNullChecks
2. Redesigned middlwears to match common syntax `(context, next) => {}`
3. Removed a lot of functionality, some of it will be ported back before switching to v2.0 version (if it will appear sometime), but some them (proxy for example) will not. You can implement proxy middleware if you want.
4. We've tried to make it as simple as possible. Core library contains nothing just one function for running middlewears and uploading images. Sessions, Stages etc are implemented as middlewears.
5. There is no dedicated way to create response now. Just return suitable to api spec json object from your command. But for most common cases we've created helper `Reply` which can generate most common replies like `Reply.text('Hello!')` or `Reply.text({text: 'Hello', tts: 'Hell+o'})`

**Comment by fletcherist** [comment]
6. Webhook server designed based on pure `http` package.
7. New concept as `Stage`, which adds relations between `Scenes`
8.


We released it yesterday, yeah ✌️
