### ISSUE TITLE
Программный выход из сцены

### ISSUE THREAD

**Issue by AntonRzevskiy** [fletcherist/yandex-dialogs-sdk#84]
Здравствуйте! Я немного запутался в сценах. Хочу сразу предупредить я с "nodejs" на вы, а с "typeScript" на "что это О_о".

Постараюсь вкратце объяснить, что мне нужно:

Я хочу создать сцену, но "матчи" для успешного выхода определить программно или в "any" парсить и выходить? как то можно так?

**Comment by fletcherist** [comment]
@AntonRzevskiy Привет! Для тебя есть несколько недокумментированных возможностей, однако реди для продакшена.
```javascript
scene.enter('Я сюда попал', ctx => ...)
scene.leave((ctx) => isTimeToLeave(ctx), ctx => ctx.reply('Вышел со сцены'))
```

Грубо говоря, просто передай первым аргументом функцию, возвращающую `boolean`, если ты вернёшь `true`, то тогда совершится выход со сцены.



**Вариант N два**

```javascript
const scene2 = new Scene('scene-2')
scene1.any(ctx => {
   ctx.enterScene(scene2) // Перейдёт на вторую сцену
   ctx.leaveScene() // Выйдет на главный сценарий
}
```

Спрашивай, если что-то ещё не ясно :)
Буду рад помочь!

**Comment by AntonRzevskiy** [comment]
Спасибо @fletcherist. Идея использовать свою функцию для "матча", мне очень нравится! Пока справился метод `ctx.leaveScene()`. Буду следить за вашим растущим проектом, надеюсь он будет идти в ногу с Алисой :)

**Comment by fletcherist** [comment]
@AntonRzevskiy мы готовим большой релиз 2.0. Он сломает обратную совместимость в некоторых местах, но будет намного круче сделан архитектурно. [Подробнее..](https://github.com/fletcherist/yandex-dialogs-sdk/issues/81)
