### ISSUE TITLE
Имя для сцены и не только?

### ISSUE THREAD

**Issue by AntonRzevskiy** [fletcherist/yandex-dialogs-sdk#85]
Создавая новую сцену, можно указать её название (имя). А можно ли задать дополнительно что то своё?
### например:
``` javascript
const game = new Scene( 'song', songs.getRandom() );
```
и потом как то обрабатывать:
``` javascript
game.command('подскажи', ctx => {

    let hint = game[ someProperty ].hint;

    return ctx.reply( hint );
});
```

**Comment by fletcherist** [comment]
if you need to show random hint to every user, you can use `ctx.state` inside the command body to generate hint.

```javascript
game.command('подскажи', ctx => {
    ctx.hint = getMyAwesomeHint()
    ctx.reply( hint );
});
```

In that case `ctx.hint` would be unique for each user.

**Comment by AntonRzevskiy** [comment]
В моём примере мне нужно для игры в песни, получить случайную песню. Могу ли я сделать это и записать в контекст или объект игры?

По завершению игры, взять новую песню и так далее?

Грубо говоря песня это уже объект с набором своих правил. Идеальный сценарий это:

1. Получил песню.
2. Прикрепил к игре.
3. Отыграл с юзером.
4. Открепил.

**Comment by fletcherist** [comment]
yep, you can do this because `ctx.state` is attached to user id.
you can store js object here, but I advise you to store just `songId` instead of full object.

1. Create a collection with songs 
```
const songs = { [songId]: [song] }
2. store `songId` in `ctx.state` after initialization.
3. flush `ctx.state.songId` after end of the game

**Comment by AntonRzevskiy** [comment]
@fletcherist спасибо! Я так и сделаю!
