### ISSUE TITLE
Непонятки с матчами команд

### ISSUE THREAD

**Issue by AntonRzevskiy** [fletcherist/yandex-dialogs-sdk#86]
Некорректно обрабатываются совпадения с массивами строк... или я чего то не понимаю
``` javascript
let game = new Scene( songs.get() ); // перегрузочка :)

game.enter(['готов', 'играть', 'начинаем', 'поехали', 'могу', 'давай'], ctx => {

    // совпадает с: "г", "и", "н", "п", "м", "д"
});

game.command(['повтори', 'подскажи', 'давай'], ctx => {

    // тоже совпадает с: "п", "д"
});

game.leave(['надоело', 'устал', 'скучно', 'стоп', 'хватит'], ctx => {

    // совпадает с: "н", "у", "с", "х"
});
```
Проще говоря с первыми буквами или неполными словами... Подскажите?

**Comment by popstas** [comment]
Совпадение массивов строк проверяется через fuse.js, там сейчас есть некоторые проблемы, можно настраивать через fuseOptions степень нечеткости поиска, но вроде он всегда совпадет с "д", если в слове есть "д".

**Comment by AntonRzevskiy** [comment]
Спасибо @popstas, что разъяснили. У [fuse.js](http://fusejs.io/) реальное непонимание `Minimum character length` такое чувство, что оно ни на что не влияет... буду учитывать это.

**Comment by fletcherist** [comment]
@AntonRzevskiy we've fully rethinked the way we do fuzzy matches in 2.0. We've decided to drop this library (*fuse.js*) in favor to our custom fuzzy implementation.

For your case, if you don't mind, please use `Matchers () => boolean` to implement your custom logic.
This `fuse.js` seems to be complete bullshit.

**Comment by fletcherist** [comment]
btw if you have some suggestions on the matchers implementation, you can always tell me about them and we'll implement it in our core architecture

**Comment by AntonRzevskiy** [comment]
@fletcherist - я могу, придумать свою реализацию логики обработки массива строк, но только на нативе, если не возражаете?

**Comment by fletcherist** [comment]
@AntonRzevskiy да даже в псевдокоде будет уже норм

**Comment by AntonRzevskiy** [comment]
Есть такая идея - https://jsfiddle.net/8po6g27a/14/
Это черновой вариант... не судите строго :) Я еще буду думать.

**Comment by AntonRzevskiy** [comment]
готовый класс + тест — https://jsfiddle.net/8po6g27a/56/
github — https://github.com/AntonRzevskiy/simple-matcher/blob/master/matcher.js
### Возможности
кое что позаимствовано у [yandex](https://yandex.ru/support/search/query-language/search-context.html)
- _В которых обязательно присутствует выделенное слово._ `+` —  пример: `+слово`
``` javascript
Matcher.add(['+слово']) => слово, пословица, словосочетание
```
- _В которых отсутствует заданное слово._  `-` —  пример: `-слово`
``` javascript
Matcher.add(['-слово']) => все что угодно кроме...
```
- _Начало слова._  `^` —  пример: `^слово`
``` javascript
Matcher.add(['^слово']) => слово, словосочетание
```
- _Окончание слова._  `$` —  пример: `слово$`
``` javascript
Matcher.add(['слово$']) => слово, полуслово
```
Конечно можно комбинировать и никто не запрещает добавить валидную регулярку.
``` javascript
Matcher.add(['+^слово$', '+..ово$', '-^в$', '-^на$', '-^что$'])
```
Количество позитивных совпадений в строке влияет на релевантность функции.

После вызова `Matcher.match` методу `call` доступны самые релевантные функции привязанные с помощью `add`. Если самых релевантных функций несколько они будут отсортированы по приоритету.

Метод `call` может получить ограниченное количество функций например:
``` javascript
Matcher.call( undefined, 1 ) // прожечь только первый колбек
```

**P.S.** Для моего проекта хватит с головой :)

**Comment by fletcherist** [comment]
@AntonRzevskiy we have released 2.0 yesterday. Our new matching algorithm is now based on [Levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance) 

It only works for strings at the moment.
For array of strings we want something similar. I'd like your idea to treat it like that
```javascript
Matcher.add(['+^слово$', '+..ово$', '-^в$', '-^на$', '-^что$'])
```
I dived deeply into your implementation, 
I think it's what we want. But I hesitate here, we need a discussion.

@popstas, @alexander-karpov what do you think about that syntax and concept at all?

**Comment by fletcherist** [comment]
Close, not actual. Feel free to reopen this, if you want to suggest something.
